project:
  type: book

book:
  title: "Building reproducible analytical pipelines with R"
  author: "Bruno Rodrigues"
  date: "1/6/2023"
  site-url: "https://github.com/b-rodrigues/rap4all"
  chapters:
    - index.qmd
    - preface.qmd
    - intro.qmd
    - part: part1_intro.qmd
      chapters:
        - prerequisites.qmd
        - project_start.qmd
        - git.qmd
        - github.qmd
        - fprog.qmd
        - lit_prog.qmd
        - part1_conclusion.qmd
    - part: part2_intro.qmd
      chapters:
        - project_rewrite.qmd
        - repro_intro.qmd
        - packages.qmd
        - testing.qmd
        - targets.qmd
        - repro_cont.qmd
        - ci_cd.qmd
        - part2_conclusion.qmd
    - references.qmd
  page-navigation: true

bibliography: references.bib

format:
  epub:
    toc:
      true
    lang:
      en-GB
    date:
      "2023-03-01"
    css:
      epub.css
  html:
    include-in-header:
      file: header.html
    theme:
      light: flatly
      dark: solar
    css:
      epub.css
  pdf:
    documentclass: scrreprt



