project:
  type: book

book:
  title: "Building reproducible analytical pipelines with R"
  author: "Bruno Rodrigues"
  date: "1/6/2023"
  site-url: "https://github.com/b-rodrigues/rap4all"
  chapters:
    - index.qmd
    - intro.qmd
    - part: part1_intro.qmd
      chapters:
        - project_start.qmd
        - git.qmd
        - github.qmd
        - fprog.qmd
        - lit_prog.qmd
        - part1_conclusion.qmd
    - part: "Part 2"
      chapters:
        - project_rewrite.qmd
        - packages.qmd
        - testing.qmd
        - targets.qmd
        - repro_intro.qmd
        - repro_cont.qmd
        - ci_cd.qmd
    - references.qmd
  page-navigation: true

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
  pdf:
    documentclass: scrreprt



