project:
  type: book

book:
  title: "Building reproducible analytical pipelines with R"
  author: "Bruno Rodrigues, ..."
  date: "1/6/2023"
  site-url: "https://github.com/b-rodrigues/rap4all"
  chapters:
    - index.qmd
    - intro.qmd
    - fprog.qmd
    - git.qmd
    - keep_dry.qmd
    - project_start.qmd
    - testing.qmd
    - packages.qmd
    - targets.qmd
    - repro_intro.qmd
    - repro_cont.qmd
    - ci_cd.qmd
    - references.qmd
  page-navigation: true

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
  pdf:
    documentclass: scrreprt



